adding bgp-tencent tests
ANISH-GOTTAPU/sonic-mgmt pull request #2
Opened 2021-02-19 14:03 UTC by ANISH-GOTTAPU

adding bgp-tencent tests

2021-02-19 15:30 UTC, ashutshkumr commented on tests/common/ixia/ixia_fixtures.py
> +def api(ixia_api_serv_ip,
we need to rename `api` to `snappi_api` or `snappi_ixnetwork_api`

2021-04-01 08:19 UTC, Rangababu-R requested changes

2021-04-01 08:19 UTC, Rangababu-R commented on tests/common/ixia/ixia_fixtures.py
> +        api.assistant.Session.remove()
If this line still throws assistant attr not found exception use getattr(api, 'assistant', None) in if condition

2021-04-29 03:00 UTC, stayyule commented
Spelling issue: Rujje->Ruijie

2021-04-29 06:27 UTC, merged